version: "3"

services:
  vmq:
    image: vmq
    ports:
      - 22345:80
    restart: always
  
  db:
    image: mysql:5.6
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=vmq
      - MYSQL_DATABASE=vmq
      - MYSQL_USER=vmq
      - MYSQL_PASSWORD=vmq
    volumes:
      - ./mysql:/var/lib/mysql
