version: '3'
services:

  web:
    image: "poorthatcher/tokenpay:ubuntu"
    container_name: tokenpay
    ports:
     - "5000:80"
     # - "5001:9001" # for supervisor web
    volumes:
     - ./appsettings.json:/tokenpay/appsettings.json
     - ./EVMChains.json:/tokenpay/EVMChains.json
     - ./nginx.conf:/etc/nginx/nginx.conf
